GitUpdateManager: Always prune when fetching (#4136)
Preemptively add this so old branch refs get pruned from git.
When we don't do this, it could lead to git erroring because it can't update the ref.
```
CHECKVERSION :: git fetch origin returned : error: cannot lock ref 'refs/remotes/origin/ui/navbar-fixed-icon-width': 'refs/remotes/origin/ui' exists; cannot create 'refs/remotes/origin/ui/navbar-fixed-icon-width'
From https://github.com/org/repo
! [new branch] ui/navbar-fixed-icon-width -> origin/ui/navbar-fixed-icon-width (unable to update local ref)
error: some local refs could not be updated; try running
'git remote prune origin' to remove any old, conflicting branches
CHECKVERSION :: Unable to contact github, can't check for update
```