Migrate all the db's to have the shows id included, making the db model multi-indexer safe (#3504)
* Migrate all the db's to have the indexer's id. Named indexer_id. This should match up with series_id eventually.

* Fix the main.db tables.

* Update the history table in failed.db.

* Add indexer to BlackAndWhiteList.

* Added indexer to failed_history.

* Started implementing multiindexer support.
Backend + frontend.

* Fixed displayShow.

* Fix coming episodes.
But the coming episodes are really not multi indexer friendly!
Maybe need to start looking at adding a row_id field to join episodes/series.

* Fix scheduler.
Something weird with the getManualSearch request.
Someone hacked this in, without any real purpose.

* Fix failed_db migration.

* Fix routes and object passing vs. id+id.

* Fixed routes in frondend.

* Refactor series_object to series_obj.

* Fixed get_xem_numbering_for_show in banner.mako.

* Removed the unique index on tvshows.
Removed PK on imdb_info, added new PK column wich is autonumbered.

* Added methods to translate indexer id to name and visa versa to the apiv2 config route.
Added js methods to core.js that can be used to translate the indexer id to name, in frondend.

* Lot's of fixups.
* Cleanup of the indexerid's to series_id.
* disabled kodi12+ metadata creation of the episodeguide for tmdb/tvmaze shows. (removed it).

* Fixed manual snatch.

* Fixed indexing episodes from tmdb.

* Fixed manage episode statussus.
Fixed manage missed subtitleShow
Fixed showSelector.mako
Fixed schedule page.
Fixed getManualSearchStatus, when no show passed.

* Fixed massUpdate and massEdit.
Fixed backlogOverview.

* Add sanitizing of scene_exceptions, removing records with null values.
* Fix passing incorrect params.

* Fixed inserting items in cache.
* Added check to snatch-selection.js to prevent loop of checking new items in cache, when the db is corrupted.

* Fixed reference to get_indexer_numbering in name parser.

* Fix rebase issue.

* Fix show selector in displayShow.

* Fix post-process history query.

* Fix massUpdate update, rescan, rename etc. actions.

* Removed debugging pass statement.

* Fix typo in proper search.

* Fix main.db data migrations.

* Create new columns with default value of null.
* Improve the speed for updating history table.

* Fix daily search, using find_show_by_id.

* Fix creation of name cache.

* Fix set episodes to status wanted, to trigger a backlog search.

* Fix calling series on a SearchResult object.
Added deprecation warning.

* Refactor searchResult show to series.

* Fix deleting shows.

* Add indexer_name to paths in the image_cache.py lib.

* Fix mass update refresh images.

* Fix episodeStatuses.
Fix EditShow save sceneexceptions.

* Fixed history compact modus.

* Fix xem refresh occurring every displayShow opening.

* Fix attempt to try to get xem mapping on every episode load. Using the episode object in stead series object.

* Missed one.

* Fix proper search. (#3565)

* Insert indexer_id in history table.
Had to standardize and cleanup history.py a little.
Like don't pass ep_obj.series.indexer + ep_obj.series.series_id + ep_obj.season + ep_obj.epiode. If we can also pass ep_obj.

* Fixed manage episode status.

* Fixed ajax-episode-search indexer series id references.

* Use background-series-slug for history.mako.

* Fix clearing the name_cache on each search, removing all name_cache entries, instead of the one i'm adding.

* Fix manageSubtitles.
* Make manageBacklog multiindexer friendly.

* Fixed testRename.

* Fixed history table in snatchSelection.

* Fixed episode statistics.

* Fix AttributeError: 'NoneType' object has no attribute 'get_episode'

* Fix adding shows using recommended lists anidb and trakt.
Imdb should also work. But unfortunately imdbpie is broken at the moment.

* Fix bug getting show image through apiv1.

* Fix BacklogOverview page.

* Fix calling show on SearchResult object.

* Fix adding new show, redirect to simple layout.

* Fix unique constraint error on the xem_refresh.

* Fix for apiv1.

* Refactor SearchResult.show to SearchResult.series.

* Refactor missing clients to series

* Fixed xo (eslint) warnings.
Changed back some of the arrow notation to function.

* Fix proper search and rename show to series

* More renaming to Series

* More renaming to Series (2)

* flake

* flake 2

* flake 3

* Typos in api v1

* Flake 4

* Add images migration for posters, banners, fanart.

* Migrate thumbnails.
* Fix the method for users that have already migrated.

* Ignore provider cache results without an indexer.

* Ignore the provider cache result, as early possible.
Also added the continue.

* Fix unexpected argument

* Fix set_scene_numbering.

* Cleanup. series_obj renames.
* series.py: Use the property to write to, instead of directly to private variable.
* image_cache.py: Fix logging the metadata provider name in stead of object.
* media/generic.py: unused imports.

* self.indexerid -> self.series_id

* flake8

* rm unused imports

* Update failed_processor.py

* Fix tests, flake, speedify tests

* Add cov-report

* Update tox.ini

* Bring back api tests

* Disable API tests once again

* Update tox.ini

* Rename to be consistent. No more missing renames

* Renamed parsed_result to parse_result

* Fixed rebase conflict.
Add check for when using the Scene Absolute column with a non-anime.

* Flake once again

* Added exception handling to the image migration.

* Moved ajax-notifications.js code to core.js because the eventListener was initialized after it was triggered.

* Removed double line.

* xo lint fix.

* show_obj -> series_obj

* Update __main__.py