Added initial IMDB indexer. (#3603)
* Added initial IMDB indexer.
Working: Searching + basic adding of show.

* Don't add video games and tv short.

* Fixed setting the imdb_id external.

* Added images (only poster for now).

* Added show status and firstaired using releases route.

* Added better support for poster and poster_thumbs.

* Added routes that still need to be added to imdbpie.py

* Fix show_url

* Fix network and images.

* Added episode rating, overview and airdate.

* Fixed bug where adding show without a summary, throwed an error.

* Added actors.
* Don't display imdb icon, when it's an imdb show, as there is already an icon shown.
* added cross-env to package.json for building.

* Added fanart and production_art (as fanart).

* Use the poster initially provided with the show, as the images api, doesn't have any ratings attached to the images.
Use the production art as fanart.
* Rename the exceptions to be used as imdb exceptions.

* Refactor indexers.
* Use get_nested_value function for tvmaze.

* Use get_nested_value() function for tmdb.
* Fixed get_nested_value for when it's getting 0 or empty strings.

* tvmaze exceptions got removed.

* Get airs day of week, from last 10 airdates.

* Added episode thumbnails with kodi_12plus.

* Fix issues with shows missing info.
* correct merge conflict.

* Fix exception for when search doesn't return any results.
The raise, was removed somewhere.

* Use templating for the show_url.
* Imdb requires the tt with appended 0's in front of the id.

* Change the addShows addShows/searchIndexersForShowName function to return a key/value pair of values.
In stead of list.
* Refactored mako for the refactor of the indexer_api to api.

* Fixed searching for The Tick.
* Search was giving duplicate results. Filtered them by unique indexer and seriesId.
* Fixed issue where it cannot get a startyear, for a distribution. My guess is, this happens with stream providers like amazon and netflix.

* Disable the delay on ShowUpdater.

* Update imdbpie to latest develop.

* Modify get_last_updated_series parameters.
Add the cache parameter, for retrieving lastUpdates of specific show+season.

* Start changing show_updater.py to add the ability of adding using per season updates when no the indexer does not provide a list of recently updated shows.

* Added per season calculated intervals for show updates.

* restored the show update delay.
Fixed bug.

* Changed per season update to show updates for imdb.

* Moved the show search in the exception handling block.

* Fix conflicts

* Fix adding shows using imdb

* And it loads the displayShow

* Fixed a number of bugs

* Fix status tmdb

* Fix method call get_last_seasons for tvdb

* Fix show_updater

* Fix get external lookups for imdb.

* Fix getting rating/contentrating from imdb.

* Fix show imdb icon for non-imdb shows

* Fix regressions on providers with absolute numbering

* fixing old merge conflicts

* Not using this

* Fix more indexer merge conflicts

* Fix more merge conflicts

* More merge conflicts

* revert the show_updater scheduler

* Fix change-indexer

* Fix season updating for imdb

* comment show_updater

* fix kodi metadata actor error

* Fix get origin_country

* Fix change-indexer

* Lots of fixes:
* Refactored the imdb id thing
* Fixed recommended shows (adding imdb)

* Fixed bug with actor without role?

* Add search imdb by id.

* fix: Add existing shows

* Make searching more flexible

* added externals component

* Get the thumb version for poster.

* Fix imdb status

* Extended tmdb exception handling.
For AttributeError: 'NoneType' object has no attribute 'raise_for_status'

* Fix error with lastaired

* Adding log for when tt id's are cleaned from indexer_mapping.

* Fix get_episode error

* Clean recommended_db

* Improve searching

* add logs

* simplify clean imdb tt

* Fix parsing images tmdb

* Fix exception handling for show_updater when updating through indexers without a per season update list like tvmaze.

* Get posters and banners by aspect_ratio

* New imdb sorting logic

* Improve the show season updates.

* Limit the amount of info pulled for checking if we need a season update.
* Only pull the season that we need.

* Also applied to the other indexers

* Refactored the get_last_updated_seasons method.

* comment

* Fix imdb id parse error

* Fix diverse imdb id mapping

* Add login response check

* Added imdb exception handling

* Fix flake warnings

* Refactor and fix flake

* Fix jest tests

Co-authored-by: supergonkas <supergonkas@gmail.com>