Fix general config not saving due to:
general.py", line 101, in saveGeneral
   sickbeard.GIT_RESET_BRANCHES = git_reset_branches.split(',') if git_reset_branches else []
AttributeError: 'list' object has no attribute 'split'